### ISSUE TITLE
What is the good way to learn the sea model?Learn 3dmax and then use sea's online editing tools?

### ISSUE THREAD

**Issue by WREQI** [lo-th/Character-sea3d#1]
**What is the good way to learn the sea model?Learn 3dmax and then use sea's online editing tools?**

**Comment by lo-th** [comment]
yes you can learn 3dsmax is a great software.
or you can use blender 3d ( last 2.8 version is very good ) and convert you files with sea Studio

**Comment by WREQI** [comment]
Well, I downloaded blender2.8 and it feels very good.
